version: '3'
services:
  server:
    build: server
    image: toomanycaptains/server
    network_mode: host
    restart: unless-stopped
    ports:
      - "9000:9000"
  scanner:
    depends_on:
      - "server"
    build: scanner
    image: toomanycaptains/scanner
    network_mode: host
    restart: unless-stopped
    privileged: true
  kiosk:
    depends_on:
      - "server"
      - "game"
      - "scanner"
    build: kiosk
    image: toomanycaptains/kiosk
    network_mode: host
    restart: unless-stopped
    environment:
      DISPLAY: ":0"
    privileged: true
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "/dev/shm:/dev/shm"
    devices:
      - "/dev/snd:/dev/snd"
    command: "--kiosk --incognito --alsa-output-device=hw:0,3 --no-first-run 'http://localhost?local&skip'"
  game:
    depends_on:
      - "server"
    build: game
    image: toomanycaptains/game
    network_mode: host
    restart: unless-stopped
    ports:
      - "80:80"
