// tslint:disable-next-line:variable-name
const AssetManifest = {
  images: [
    'title.png',
    // 'planet.png',
    'background.png',
    'gameover-text.png',
    'red-button.png',
    'asteroid.png',

    'door-left.png',
    'door-right.png',

    'enemy_bullet_R.png',
    'enemy_bullet_B.png',
    'enemy_bullet_Y.png',

    'player_bullet_R.png',
    'player_bullet_B.png',
    'player_bullet_Y.png',

    'shield_B.png',
    'shield_BY.png',
    'shield_BRY.png',
    'shield_BR.png',
    'shield_R.png',
    'shield_RY.png',
    'shield_Y.png',

    'icon-weapons.png',
    'icon-shields.png',
    'icon-thrusters.png',
    'icon-repairs.png',
    // new BIG icons -- March 13th
    'icon-big-weapons.png',
    'icon-big-shields.png',
    'icon-big-thrusters.png',
    'icon-big-repairs.png',

    'icon-mask.png',
    // new masks with names of subsystem -- March 13th
    'icon-mask-weapons.png',
    'icon-mask-shields.png',
    'icon-mask-thrusters.png',
    'icon-mask-repairs.png',

    'ring-B.png',
    'ring-BY.png',
    'ring-BRY.png',
    'ring-BR.png',
    'ring-R.png',
    'ring-RY.png',
    'ring-Y.png',
    'ring-thrusters.png',
    'ring-repairs.png',
    'ring-none.png',

    'captain-icon-amber.png',
    'captain-icon-brick.png',
    'captain-icon-hickory.png',
    'captain-icon-iris.png',
    'captain-icon-jade.png',
    'captain-icon-razzmic.png',

    'map.png',
    'map-icon-player.png',
  ],
  sprites: [],
  audio: [
    'shoot.mp3',
    'move_slow.mp3',
    'move_fast.mp3',
    'doors_opening.mp3',
    'doors_closing.mp3',
    'explosion.mp3',
    'shield.mp3',
    'damaged.mp3',
    'collide.mp3',
    'gameover.mp3',
    'scan_success.mp3',
    'scan_fail.mp3',
    'shield_hit_B.mp3',
    'shield_hit_R.mp3',
    'shield_hit_Y.mp3',
    'shield_on_B.mp3',
    'shield_on_R.mp3',
    'shield_on_Y.mp3',
    'wrong_weapon.mp3',
    'repairs.mp3',
    'health_low.mp3',
    'health_very_low.mp3',
    'music_background.mp3',
    'music_stage_1.mp3',
    'music_stage_2.mp3',
    'music_stage_3.mp3',
    'music_stage_4.mp3',
  ],
  fonts: {
    custom: {
      families: ['Exo 2:600,700,800,900'],
    },
  },
};

export default AssetManifest;
