const AssetManifest = {
  images: [
    'title.png',
    // 'planet.png',
    'background.png',
    'gameover-text.png',
    'red-button.png',
    'asteroid.png',

    'door-left.png',
    'door-right.png',

    'beam_B.png',
    'beam_R.png',
    'beam_Y.png',

    'bullet_new_R.png',
    'bullet_new_B.png',
    'bullet_new_Y.png',

    'shield_B.png',
    'shield_BY.png',
    'shield_BRY.png',
    'shield_BR.png',
    'shield_R.png',
    'shield_RY.png',
    'shield_Y.png',

    'icon-weapons.png',
    'icon-shields.png',
    'icon-thrusters.png',
    'icon-repairs.png',

    'icon-mask.png',

    'ring-B.png',
    'ring-BY.png',
    'ring-BRY.png',
    'ring-BR.png',
    'ring-R.png',
    'ring-RY.png',
    'ring-Y.png',
    'ring-thrusters.png',
    'ring-repairs.png',
    'ring-none.png',

    'mini_map.png',
    'player_icon.png',
    'boss_icon.png',
  ],
  sprites: [],
  audio: [
    'shoot.wav',
    'move_slow.wav',
    'move_fast.wav',
    'charging.wav',
    'doors_opening.wav',
    'doors_closing.wav',
    'explosion.wav',
    'shield.wav',
    'damaged.wav',
    'collide.wav',
    'gameover.wav',
    'scan_success.wav',
    'scan_fail.wav',
    'shield_hit_B.wav',
    'shield_hit_R.wav',
    'shield_hit_Y.wav',
    'shield_on_B.wav',
    'shield_on_R.wav',
    'shield_on_Y.wav',
    'wrong_weapon.wav',
    'repairs.wav',
    'health_low.wav',
    'health_very_low.wav',
    'music_stage_1.wav',
    'music_stage_2.wav',
    'music_stage_3.wav',
    'music_stage_4.wav',
  ],
  fonts: {
    custom: {
      families: ['Exo 2:600,700,800,900'],
    },
  },
};

export default AssetManifest;
